### ISSUE TITLE
Hoppers work normally initially, but then stop catching items from the world

### ISSUE THREAD

**Issue by Borbarad13** [Shorepion/Magica-Infinitum-III#20]
*Thank you for reporting an issue!
Please make sure to give answers for the following:*

## 1) Which Modpack version are you using?
1.16.5-3.3.5
 
## 2) Link to the crashlog (found in the crash-reports folder).
 No crash.
 
## 3) Detailed description of the issue and if possible pls attach images
Hoppers pick up items from the world after you place them. However, after a while they stop doing that (although the hopper is empty and not redstone powered). 
Here for example the hopper doesn't pick the food item, although the hopper should: 

![2022-01-05_01 18 10](https://user-images.githubusercontent.com/16468773/148137942-62bd3599-77ec-4815-98af-30f6d53d322c.png)

## 4) Is the issue repeatable?
Yes.
 
## 5) Do you know a possible fix for the issue?
No. Maybe it's even intentional. Not sure which mod modifies the hoppers.

**Comment by Shorepion** [comment]
After some testing it turns out that the vanilla behavior of hoppers will be overwritten by Better Hopper (Hopper+) content, when playing in a Multiplayer/LAN world.
To 'fix' this you can put a 'Vacuum Upgrade' from 'hopperplus' in the hopper, which will then suck in the items.

Unfortunately there is no config file for tweaking 'hopperplus' content.

Just as a side note: I will remove **Better Hoppers (Hopper+)** and the **GoldenHopper** mod, which were added in the first version of this modpack to have some "more advanced" logistics, because to that time there was a bit of lack of magic themed logistic systems. But now we have quite some better and more theme fitting item transportation options (Translocators, Occultism Storage, Blood Magic...)
